nelmio_api_doc:
    documentation:
        info:
            title: API BileMo
            description: BileMo API documentation
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Value: Bearer {jwt}'
                    in: header
                    name: Authorization
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                Customer:
                    properties:
                        email:
                            type: string
                        password:
                            type: string
        security:
            - Bearer: [ ]

        paths:
            /api/login:
                post:
                    summary: "Allow customer to authenticate to api and obtain token / refresh token"
                    tags:
                        - Global

                    requestBody:
                        description: Optional description in *Markdown*
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Customer'

                    responses:
                        500:
                            description: "Internal server authentication"
                        401:
                            description: "Invalid credentials"
                        200:
                            description: "Login success"
            /api/doc.json:
                get:
                    tags:
                        - Global
                    summary: "Obtain documentation on json format"
                    responses:
                        200:
                            description: "Get API documentation in json format"
    areas:
        path_patterns:
            - ^/api(?!/doc$)
